server:
  port: 8080
  servlet:
    context-path: /api
spring:
  output:
    ansi:
      enabled: always
  datasource:
    #    url: jdbc:postgresql://localhost:5432/test?currentSchema=public&characterEncoding=utf8
    #    url: jdbc:h2:mem:testdb
    #    driver-class-name: org.h2.Driver
    url: jdbc:mysql://152.67.204.212:3306/zmpt_cc?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: zmpt_cc
    password: tdKKzt3CsCpfMP48
  threads:
    virtual:
      enabled: true
  application:
    name: pdpt-server
  jpa:
    hibernate:
      ddl-auto: validate
    #      ddl-auto: create-drop
    generate-ddl: false
    show-sql: true
    properties:
      show-sql: true
      use_sql_comments: true
      format_sql: true
      type: trace
#    open-in-view: false
logging:
  level:
    #    web: debug
    org.springframework.data: debug
    org.hibernate.SQL: debug
    org.hibernate.stat: debug
    org.hibernate.SQL_SLOW: debug
    org.hibernate.cache: debug
    org.hibernate.orm.jdbc.bind: trace
