---
spring:
  datasource:
    url: jdbc:mysql://195.201.132.61:3306/pdpt?serverTimezone=Asia/Shanghai
  config:
    activate:
      on-profile: dev
---
server:
  port: 8080
  servlet:
    context-path: /api
spring:
  output:
    ansi:
      enabled: always
  datasource:
    #    url: jdbc:postgresql://localhost:5432/test?currentSchema=public&characterEncoding=utf8
    #    url: jdbc:h2:mem:testdb
    #    driver-class-name: org.h2.Driver
#    url: jdbc:mysql://152.67.204.212:3306/zmpt_cc?serverTimezone=Asia/Shanghai
    url: jdbc:mysql://ds923plus:3306/pdpt?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: test123
  threads:
    virtual:
      enabled: true
  application:
    name: pdpt-server
  jpa:
    hibernate:
      ddl-auto: validate
    #      ddl-auto: create-drop
    generate-ddl: false
    show-sql: true
    properties:
      show-sql: true
      use_sql_comments: true
      format_sql: true
      type: trace
#    open-in-view: false
app.accepted-urls:
    - /auth/login
logging:
  level:
    web: debug
    org.springframework.data: debug
    org.hibernate.SQL: debug
    org.hibernate.stat: debug
    org.hibernate.SQL_SLOW: debug
    org.hibernate.cache: debug
    org.hibernate.orm.jdbc.bind: trace
